export const PRODUCTS_BY_TARIFF: Record<string, string[]> = {
  "2.0TD": [
    "Index Base",
    "Index Coste",
    "Index Promo",
    "Fijo Fácil",
    "Fijo Estable",
    "Fijo Snap",
    //"Fijo Snap Fresh",
    "Fijo Snap Maxi",
    "Fijo Snap Mini",
    "Passpool",
  ],
  "3.0TD": [
    "Index Base",
    "Index Coste",
    "Index Promo",
    "Fijo Fácil",
    "Fijo Estable",
    "Fijo Dyn",
    "Passpool",
    "Promo 3M Lite",
    "Promo 3M Pro",
    "Promo 3M Plus",
  ],
  "6.1TD": [
    "Index Base",
    "Index Coste",
    "Index Promo",
    "Fijo Fácil",
    "Fijo Estable",
    "Fijo Dyn",
    "Passpool",
    "Promo 3M Lite",
    "Promo 3M Pro",
    "Promo 3M Plus",
  ],
};
